enum {
	FACTORY_MODEL_COLUMN_TYPE,
	FACTORY_MODEL_COLUMN_PROFILE,
	FACTORY_MODEL_COLUMN_MODEL,
	FACTORY_MODEL_COLUMN_ID,
	FACTORY_MODEL_NUM_COLUMNS
};

/* We use these for sorting */
enum {
	FACTORY_MODEL_TYPE_INFO,
	FACTORY_MODEL_TYPE_DCP,
	FACTORY_MODEL_TYPE_ICC,
	FACTORY_MODEL_TYPE_SEP,
	FACTORY_MODEL_TYPE_ADD,
};
